server:
  port: 20001
  address: 0.0.0.0
spring:
  # 关闭spring data的redis仓库，否则启动时会有这种日志Spring Data Redis - Could not safely identify
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    # driver-class-name: com.mysql.jdbc.Driver
    # url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/test_jpa?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:asdf;lkj123!@#}
    # 连接池配置，Spring Boot 2.0以后默认使用 HikariCP 连接池，2.0以前默认使用的是 Tomcat 连接池
    hikari:
      pool-name: HikariPool
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      idle-timeout: 600000 # 空闲连接存活最大时间，默认600000（10分钟）
      max-lifetime: 1800000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟

#hibernate JPA
  jpa:
    # database: MYSQL
    database: postgresql
    #配置是否自动创建数据库表
    generate-ddl: true
    #设置为true：Spring Boot整合JPA后Hibernate的Session就交付给Spring去管理。每次数据库操作后，会关闭Session，当我们想要用懒加载方式去获得数据的时候，原来的Session已经关闭，不能获取数据
    #设置为false：防止hibernate的session外延到controller
    open-in-view: false
    #显示sql语句，和下面日志放开一个就行
    # show-sql: true
    hibernate:
    #在springboot项目中使用springdata Jpa，并且希望当我的实体类发生了更改，数据库表结构随着实体类的改变而自动做出相应的改变。  
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #格式化sql
        # dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        # current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        # enable_lazy_load_no_trans: true # 开启懒加载,不开启在实体类中使用 FetchType.LAZY 会报错

  redis:
    host: ${REDIS_HOST:localhost} # Redis服务器地址
    database: ${REDIS_DATABASE:0} # Redis数据库索引（默认为0）
    port: ${REDIS_PORT:6379} # Redis服务器连接端口
    # password: ${REDIS_PASSWORD:dfe69c50663c425334d06f940ded0e31}  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
    lettuce: # SpringBoot2.0默认采用Lettuce客户端来连接Redis服务端的
      pool:
        max-idle: 8 # 连接池中的最大空闲连接 
        min-idle: 0 # 连接池中的最小空闲连接
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）

logging:
  level:
    org.hibernate.SQL: debug # hibernate的sql日志级别（会打印出请求的sql）
    org.hibernate.type.descriptor.sql.BasicBinder: trace # 显示?的参数

redisCahe:
  expireTime: 3600 # redis的默认存储时长（秒）